### ISSUE TITLE
can we encrypt the password parameter?

### ISSUE THREAD

**Issue by longfei-zhang** [StackStorm-Exchange/stackstorm-email#12]
I don't want other user see the password directly.
so maybe we can add the value like:

```yaml
---
smtp_accounts:
  - name: me
    password: "I'm encrypted"
```
If so then st2 need to decrypt it first and then use it.

**Comment by nmaludy** [comment]
@longfei-zhang i'm guessing this is for the email pack? The password property is set to secret https://github.com/StackStorm-Exchange/stackstorm-email/blob/master/config.schema.yaml#L27

You could store your password in the datastore, and then retrieve it in the config using Jinja.

Since the `password` property in the config is set to secret, we need to encrypt the data in the datastore (the `-e` flag does this)

```
# save your password into the datastore
$ st2 key set -e smtp_account.me.password "I'm Encrypted"
```

Modify your email pack config `/opt/stackstorm/configs/email.yaml`

```
---
smtp_accounts:
  - name: name
    password: "{{ st2kv.system.smtp_account.me.password }}"
```
