### ISSUE TITLE
smtp must be configured within imap_mailboxes

### ISSUE THREAD

**Issue by mickmcgrath13** [StackStorm-Exchange/stackstorm-email#6]
I was having trouble sending an email with the email pack, and it wasn't until I configured my smtp mailbox within the [imap_mailboxes](https://github.com/StackStorm-Exchange/stackstorm-email/blob/master/email.yaml.example#L2) list that it was actually able to send.

This is highly counterintuitive, and I suggest separating out the imap and smtp mailboxes into separate lists.

**Comment by mickmcgrath13** [comment]
Additionally, fwiw, because there is an smtp mailbox configured within the imap_mailboxes list, the sensor was failing and not being registered.  I temporarily modified `/opt/stackstorm/packs/email/sensors/imap_sensor.py` to not try to register the smtp sensor as an imap sensor by checking for `SMTP: True` on the [imap_mailbox](https://github.com/StackStorm-Exchange/stackstorm-email/blob/master/sensors/imap_sensor.py#L79)

This hack should be able to be removed from our code once a new configuration setup has been released.

**Comment by LindsayHill** [comment]
Ah, that's a good point about having multiple imap_mailboxes configured - it will want to use them all for the IMAP sensor if that is enabled. So yeah, it seems like a good idea to break it out. Rather than nibble at the edges of it, it seems like it would be better to start from a blank sheet of paper, and re-think the pack requirements. Once that's figured out, then update the code. I think most of the code pieces are already there, and it probably doesn't need a huge amount done there - it's more of a design problem than a code problem.

**Comment by warrenvw** [comment]
Please review the following requirements and configuration file...

Configuration Requirements:

 - Send email using a remote SMTP server with/without TLS, and with/without authentication.
 - Monitor one or more IMAP mailboxes for new items, raising a trigger instance when a new email is seen.
 - Receive inbound email via SMTP, and dispatch a trigger instance when new email is seen.

Should be able to configure those independently, might use the same credentials for sending & receiving email, but the imap/smtp servers will be different, with different ports, etc.

All configuration options should be obvious, I should not be configuring SMTP servers underneath `imap_mailboxes`.

References: https://www.fastmail.com/help/technical/ssltlsstarttls.html

```
---
sensor_smtp_listen_ip: '127.0.0.1'
sensor_smtp_listen_port: 25
max_attachment_size: 1024
attachment_datastore_ttl: 1800
smtp_accounts:
  - name: personal
    server: "smtp.gmail.com"
    port: 587
    username: "lindsay@stackstorm.com"
    password: "super_S3c4e3t!"
    secure: true
    smtp_auth: true
  - name: work
    server: "imap.example.com"
    port: 465  # this is a deprecated, nonstandard port
    username: "fake@example.com"
    password: "fakepwd"
    secure: true
    smtp_auth: true
imap_accounts:
  - name: personal
    server: "imap.gmail.com"
    port: 993
    username: ""
    password: "super_S3c4e3t!"
    secure: true
  - name: work
    server: "imap.example.com"
    port: 993
    username: "fake@example.com"
    password: "fakepwd"
    secure: true
```
